language: go

sudo: required
dist: trusty

go:
  - "1.9"

install:
  - go get github.com/onsi/ginkgo/ginkgo
  - go get github.com/onsi/gomega
  - go get -u github.com/golang/lint/golint
  - curl https://glide.sh/get | sh
  - glide install

script:
  - make

after_success:
  - bash <(curl -s https://codecov.io/bash)
